/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'ResultMsg'
 * message type.
 */

package netTest.serial;

public class ResultMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 52;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 12;

    /** Create a new ResultMsg of size 52. */
    public ResultMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new ResultMsg of the given data_length. */
    public ResultMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ResultMsg with the given data_length
     * and base offset.
     */
    public ResultMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ResultMsg using the given byte array
     * as backing store.
     */
    public ResultMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ResultMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public ResultMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ResultMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public ResultMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ResultMsg embedded in the given message
     * at the given base offset.
     */
    public ResultMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ResultMsg embedded in the given message
     * at the given base offset and length.
     */
    public ResultMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <ResultMsg> \n";
      try {
        s += "  [rep_seq_no=0x"+Long.toHexString(get_rep_seq_no())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data_msg.temperature=0x"+Long.toHexString(get_data_msg_temperature())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data_msg.humidity=0x"+Long.toHexString(get_data_msg_humidity())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data_msg.voltage=0x"+Long.toHexString(get_data_msg_voltage())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data_msg.routing_data.node_addr=0x"+Long.toHexString(get_data_msg_routing_data_node_addr())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data_msg.routing_data.seq_no=0x"+Long.toHexString(get_data_msg_routing_data_seq_no())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data_msg.routing_data.ack_received=0x"+Long.toHexString(get_data_msg_routing_data_ack_received())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data_msg.routing_data.beacons=0x"+Long.toHexString(get_data_msg_routing_data_beacons())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data_msg.routing_data.ack_failed=0x"+Long.toHexString(get_data_msg_routing_data_ack_failed())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data_msg.routing_data.tx_queue_full=0x"+Long.toHexString(get_data_msg_routing_data_tx_queue_full())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data_msg.routing_data.dropped_duplicates=0x"+Long.toHexString(get_data_msg_routing_data_dropped_duplicates())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data_msg.routing_data.parents_seen=0x"+Long.toHexString(get_data_msg_routing_data_parents_seen())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data_msg.routing_data.parents_no=0x"+Long.toHexString(get_data_msg_routing_data_parents_no())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data_msg.routing_data.parents.addr=";
        for (int i = 0; i < 3; i++) {
          s += "0x"+Long.toHexString(getElement_data_msg_routing_data_parents_addr(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data_msg.routing_data.parents.etx=";
        for (int i = 0; i < 3; i++) {
          s += "0x"+Long.toHexString(getElement_data_msg_routing_data_parents_etx(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data_msg.routing_data.parents.periods=";
        for (int i = 0; i < 3; i++) {
          s += "0x"+Long.toHexString(getElement_data_msg_routing_data_parents_periods(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data_msg.routing_data.parents.subunits=";
        for (int i = 0; i < 3; i++) {
          s += "0x"+Long.toHexString(getElement_data_msg_routing_data_parents_subunits(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: rep_seq_no
    //   Field type: long
    //   Offset (bits): 0
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'rep_seq_no' is signed (false).
     */
    public static boolean isSigned_rep_seq_no() {
        return false;
    }

    /**
     * Return whether the field 'rep_seq_no' is an array (false).
     */
    public static boolean isArray_rep_seq_no() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'rep_seq_no'
     */
    public static int offset_rep_seq_no() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'rep_seq_no'
     */
    public static int offsetBits_rep_seq_no() {
        return 0;
    }

    /**
     * Return the value (as a long) of the field 'rep_seq_no'
     */
    public long get_rep_seq_no() {
        return (long)getUIntBEElement(offsetBits_rep_seq_no(), 32);
    }

    /**
     * Set the value of the field 'rep_seq_no'
     */
    public void set_rep_seq_no(long value) {
        setUIntBEElement(offsetBits_rep_seq_no(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'rep_seq_no'
     */
    public static int size_rep_seq_no() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'rep_seq_no'
     */
    public static int sizeBits_rep_seq_no() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data_msg.temperature
    //   Field type: int
    //   Offset (bits): 32
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data_msg.temperature' is signed (false).
     */
    public static boolean isSigned_data_msg_temperature() {
        return false;
    }

    /**
     * Return whether the field 'data_msg.temperature' is an array (false).
     */
    public static boolean isArray_data_msg_temperature() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'data_msg.temperature'
     */
    public static int offset_data_msg_temperature() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data_msg.temperature'
     */
    public static int offsetBits_data_msg_temperature() {
        return 32;
    }

    /**
     * Return the value (as a int) of the field 'data_msg.temperature'
     */
    public int get_data_msg_temperature() {
        return (int)getUIntBEElement(offsetBits_data_msg_temperature(), 16);
    }

    /**
     * Set the value of the field 'data_msg.temperature'
     */
    public void set_data_msg_temperature(int value) {
        setUIntBEElement(offsetBits_data_msg_temperature(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'data_msg.temperature'
     */
    public static int size_data_msg_temperature() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'data_msg.temperature'
     */
    public static int sizeBits_data_msg_temperature() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data_msg.humidity
    //   Field type: int
    //   Offset (bits): 48
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data_msg.humidity' is signed (false).
     */
    public static boolean isSigned_data_msg_humidity() {
        return false;
    }

    /**
     * Return whether the field 'data_msg.humidity' is an array (false).
     */
    public static boolean isArray_data_msg_humidity() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'data_msg.humidity'
     */
    public static int offset_data_msg_humidity() {
        return (48 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data_msg.humidity'
     */
    public static int offsetBits_data_msg_humidity() {
        return 48;
    }

    /**
     * Return the value (as a int) of the field 'data_msg.humidity'
     */
    public int get_data_msg_humidity() {
        return (int)getUIntBEElement(offsetBits_data_msg_humidity(), 16);
    }

    /**
     * Set the value of the field 'data_msg.humidity'
     */
    public void set_data_msg_humidity(int value) {
        setUIntBEElement(offsetBits_data_msg_humidity(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'data_msg.humidity'
     */
    public static int size_data_msg_humidity() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'data_msg.humidity'
     */
    public static int sizeBits_data_msg_humidity() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data_msg.voltage
    //   Field type: int
    //   Offset (bits): 64
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data_msg.voltage' is signed (false).
     */
    public static boolean isSigned_data_msg_voltage() {
        return false;
    }

    /**
     * Return whether the field 'data_msg.voltage' is an array (false).
     */
    public static boolean isArray_data_msg_voltage() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'data_msg.voltage'
     */
    public static int offset_data_msg_voltage() {
        return (64 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data_msg.voltage'
     */
    public static int offsetBits_data_msg_voltage() {
        return 64;
    }

    /**
     * Return the value (as a int) of the field 'data_msg.voltage'
     */
    public int get_data_msg_voltage() {
        return (int)getUIntBEElement(offsetBits_data_msg_voltage(), 16);
    }

    /**
     * Set the value of the field 'data_msg.voltage'
     */
    public void set_data_msg_voltage(int value) {
        setUIntBEElement(offsetBits_data_msg_voltage(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'data_msg.voltage'
     */
    public static int size_data_msg_voltage() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'data_msg.voltage'
     */
    public static int sizeBits_data_msg_voltage() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data_msg.routing_data.node_addr
    //   Field type: int
    //   Offset (bits): 80
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data_msg.routing_data.node_addr' is signed (false).
     */
    public static boolean isSigned_data_msg_routing_data_node_addr() {
        return false;
    }

    /**
     * Return whether the field 'data_msg.routing_data.node_addr' is an array (false).
     */
    public static boolean isArray_data_msg_routing_data_node_addr() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'data_msg.routing_data.node_addr'
     */
    public static int offset_data_msg_routing_data_node_addr() {
        return (80 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data_msg.routing_data.node_addr'
     */
    public static int offsetBits_data_msg_routing_data_node_addr() {
        return 80;
    }

    /**
     * Return the value (as a int) of the field 'data_msg.routing_data.node_addr'
     */
    public int get_data_msg_routing_data_node_addr() {
        return (int)getUIntBEElement(offsetBits_data_msg_routing_data_node_addr(), 16);
    }

    /**
     * Set the value of the field 'data_msg.routing_data.node_addr'
     */
    public void set_data_msg_routing_data_node_addr(int value) {
        setUIntBEElement(offsetBits_data_msg_routing_data_node_addr(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'data_msg.routing_data.node_addr'
     */
    public static int size_data_msg_routing_data_node_addr() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'data_msg.routing_data.node_addr'
     */
    public static int sizeBits_data_msg_routing_data_node_addr() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data_msg.routing_data.seq_no
    //   Field type: int
    //   Offset (bits): 96
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data_msg.routing_data.seq_no' is signed (false).
     */
    public static boolean isSigned_data_msg_routing_data_seq_no() {
        return false;
    }

    /**
     * Return whether the field 'data_msg.routing_data.seq_no' is an array (false).
     */
    public static boolean isArray_data_msg_routing_data_seq_no() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'data_msg.routing_data.seq_no'
     */
    public static int offset_data_msg_routing_data_seq_no() {
        return (96 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data_msg.routing_data.seq_no'
     */
    public static int offsetBits_data_msg_routing_data_seq_no() {
        return 96;
    }

    /**
     * Return the value (as a int) of the field 'data_msg.routing_data.seq_no'
     */
    public int get_data_msg_routing_data_seq_no() {
        return (int)getUIntBEElement(offsetBits_data_msg_routing_data_seq_no(), 16);
    }

    /**
     * Set the value of the field 'data_msg.routing_data.seq_no'
     */
    public void set_data_msg_routing_data_seq_no(int value) {
        setUIntBEElement(offsetBits_data_msg_routing_data_seq_no(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'data_msg.routing_data.seq_no'
     */
    public static int size_data_msg_routing_data_seq_no() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'data_msg.routing_data.seq_no'
     */
    public static int sizeBits_data_msg_routing_data_seq_no() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data_msg.routing_data.ack_received
    //   Field type: int
    //   Offset (bits): 112
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data_msg.routing_data.ack_received' is signed (false).
     */
    public static boolean isSigned_data_msg_routing_data_ack_received() {
        return false;
    }

    /**
     * Return whether the field 'data_msg.routing_data.ack_received' is an array (false).
     */
    public static boolean isArray_data_msg_routing_data_ack_received() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'data_msg.routing_data.ack_received'
     */
    public static int offset_data_msg_routing_data_ack_received() {
        return (112 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data_msg.routing_data.ack_received'
     */
    public static int offsetBits_data_msg_routing_data_ack_received() {
        return 112;
    }

    /**
     * Return the value (as a int) of the field 'data_msg.routing_data.ack_received'
     */
    public int get_data_msg_routing_data_ack_received() {
        return (int)getUIntBEElement(offsetBits_data_msg_routing_data_ack_received(), 16);
    }

    /**
     * Set the value of the field 'data_msg.routing_data.ack_received'
     */
    public void set_data_msg_routing_data_ack_received(int value) {
        setUIntBEElement(offsetBits_data_msg_routing_data_ack_received(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'data_msg.routing_data.ack_received'
     */
    public static int size_data_msg_routing_data_ack_received() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'data_msg.routing_data.ack_received'
     */
    public static int sizeBits_data_msg_routing_data_ack_received() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data_msg.routing_data.beacons
    //   Field type: int
    //   Offset (bits): 128
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data_msg.routing_data.beacons' is signed (false).
     */
    public static boolean isSigned_data_msg_routing_data_beacons() {
        return false;
    }

    /**
     * Return whether the field 'data_msg.routing_data.beacons' is an array (false).
     */
    public static boolean isArray_data_msg_routing_data_beacons() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'data_msg.routing_data.beacons'
     */
    public static int offset_data_msg_routing_data_beacons() {
        return (128 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data_msg.routing_data.beacons'
     */
    public static int offsetBits_data_msg_routing_data_beacons() {
        return 128;
    }

    /**
     * Return the value (as a int) of the field 'data_msg.routing_data.beacons'
     */
    public int get_data_msg_routing_data_beacons() {
        return (int)getUIntBEElement(offsetBits_data_msg_routing_data_beacons(), 16);
    }

    /**
     * Set the value of the field 'data_msg.routing_data.beacons'
     */
    public void set_data_msg_routing_data_beacons(int value) {
        setUIntBEElement(offsetBits_data_msg_routing_data_beacons(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'data_msg.routing_data.beacons'
     */
    public static int size_data_msg_routing_data_beacons() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'data_msg.routing_data.beacons'
     */
    public static int sizeBits_data_msg_routing_data_beacons() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data_msg.routing_data.ack_failed
    //   Field type: int
    //   Offset (bits): 144
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data_msg.routing_data.ack_failed' is signed (false).
     */
    public static boolean isSigned_data_msg_routing_data_ack_failed() {
        return false;
    }

    /**
     * Return whether the field 'data_msg.routing_data.ack_failed' is an array (false).
     */
    public static boolean isArray_data_msg_routing_data_ack_failed() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'data_msg.routing_data.ack_failed'
     */
    public static int offset_data_msg_routing_data_ack_failed() {
        return (144 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data_msg.routing_data.ack_failed'
     */
    public static int offsetBits_data_msg_routing_data_ack_failed() {
        return 144;
    }

    /**
     * Return the value (as a int) of the field 'data_msg.routing_data.ack_failed'
     */
    public int get_data_msg_routing_data_ack_failed() {
        return (int)getUIntBEElement(offsetBits_data_msg_routing_data_ack_failed(), 16);
    }

    /**
     * Set the value of the field 'data_msg.routing_data.ack_failed'
     */
    public void set_data_msg_routing_data_ack_failed(int value) {
        setUIntBEElement(offsetBits_data_msg_routing_data_ack_failed(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'data_msg.routing_data.ack_failed'
     */
    public static int size_data_msg_routing_data_ack_failed() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'data_msg.routing_data.ack_failed'
     */
    public static int sizeBits_data_msg_routing_data_ack_failed() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data_msg.routing_data.tx_queue_full
    //   Field type: int
    //   Offset (bits): 160
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data_msg.routing_data.tx_queue_full' is signed (false).
     */
    public static boolean isSigned_data_msg_routing_data_tx_queue_full() {
        return false;
    }

    /**
     * Return whether the field 'data_msg.routing_data.tx_queue_full' is an array (false).
     */
    public static boolean isArray_data_msg_routing_data_tx_queue_full() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'data_msg.routing_data.tx_queue_full'
     */
    public static int offset_data_msg_routing_data_tx_queue_full() {
        return (160 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data_msg.routing_data.tx_queue_full'
     */
    public static int offsetBits_data_msg_routing_data_tx_queue_full() {
        return 160;
    }

    /**
     * Return the value (as a int) of the field 'data_msg.routing_data.tx_queue_full'
     */
    public int get_data_msg_routing_data_tx_queue_full() {
        return (int)getUIntBEElement(offsetBits_data_msg_routing_data_tx_queue_full(), 16);
    }

    /**
     * Set the value of the field 'data_msg.routing_data.tx_queue_full'
     */
    public void set_data_msg_routing_data_tx_queue_full(int value) {
        setUIntBEElement(offsetBits_data_msg_routing_data_tx_queue_full(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'data_msg.routing_data.tx_queue_full'
     */
    public static int size_data_msg_routing_data_tx_queue_full() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'data_msg.routing_data.tx_queue_full'
     */
    public static int sizeBits_data_msg_routing_data_tx_queue_full() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data_msg.routing_data.dropped_duplicates
    //   Field type: int
    //   Offset (bits): 176
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data_msg.routing_data.dropped_duplicates' is signed (false).
     */
    public static boolean isSigned_data_msg_routing_data_dropped_duplicates() {
        return false;
    }

    /**
     * Return whether the field 'data_msg.routing_data.dropped_duplicates' is an array (false).
     */
    public static boolean isArray_data_msg_routing_data_dropped_duplicates() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'data_msg.routing_data.dropped_duplicates'
     */
    public static int offset_data_msg_routing_data_dropped_duplicates() {
        return (176 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data_msg.routing_data.dropped_duplicates'
     */
    public static int offsetBits_data_msg_routing_data_dropped_duplicates() {
        return 176;
    }

    /**
     * Return the value (as a int) of the field 'data_msg.routing_data.dropped_duplicates'
     */
    public int get_data_msg_routing_data_dropped_duplicates() {
        return (int)getUIntBEElement(offsetBits_data_msg_routing_data_dropped_duplicates(), 16);
    }

    /**
     * Set the value of the field 'data_msg.routing_data.dropped_duplicates'
     */
    public void set_data_msg_routing_data_dropped_duplicates(int value) {
        setUIntBEElement(offsetBits_data_msg_routing_data_dropped_duplicates(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'data_msg.routing_data.dropped_duplicates'
     */
    public static int size_data_msg_routing_data_dropped_duplicates() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'data_msg.routing_data.dropped_duplicates'
     */
    public static int sizeBits_data_msg_routing_data_dropped_duplicates() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data_msg.routing_data.parents_seen
    //   Field type: int
    //   Offset (bits): 192
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data_msg.routing_data.parents_seen' is signed (false).
     */
    public static boolean isSigned_data_msg_routing_data_parents_seen() {
        return false;
    }

    /**
     * Return whether the field 'data_msg.routing_data.parents_seen' is an array (false).
     */
    public static boolean isArray_data_msg_routing_data_parents_seen() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'data_msg.routing_data.parents_seen'
     */
    public static int offset_data_msg_routing_data_parents_seen() {
        return (192 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data_msg.routing_data.parents_seen'
     */
    public static int offsetBits_data_msg_routing_data_parents_seen() {
        return 192;
    }

    /**
     * Return the value (as a int) of the field 'data_msg.routing_data.parents_seen'
     */
    public int get_data_msg_routing_data_parents_seen() {
        return (int)getUIntBEElement(offsetBits_data_msg_routing_data_parents_seen(), 16);
    }

    /**
     * Set the value of the field 'data_msg.routing_data.parents_seen'
     */
    public void set_data_msg_routing_data_parents_seen(int value) {
        setUIntBEElement(offsetBits_data_msg_routing_data_parents_seen(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'data_msg.routing_data.parents_seen'
     */
    public static int size_data_msg_routing_data_parents_seen() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'data_msg.routing_data.parents_seen'
     */
    public static int sizeBits_data_msg_routing_data_parents_seen() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data_msg.routing_data.parents_no
    //   Field type: int
    //   Offset (bits): 208
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data_msg.routing_data.parents_no' is signed (false).
     */
    public static boolean isSigned_data_msg_routing_data_parents_no() {
        return false;
    }

    /**
     * Return whether the field 'data_msg.routing_data.parents_no' is an array (false).
     */
    public static boolean isArray_data_msg_routing_data_parents_no() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'data_msg.routing_data.parents_no'
     */
    public static int offset_data_msg_routing_data_parents_no() {
        return (208 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data_msg.routing_data.parents_no'
     */
    public static int offsetBits_data_msg_routing_data_parents_no() {
        return 208;
    }

    /**
     * Return the value (as a int) of the field 'data_msg.routing_data.parents_no'
     */
    public int get_data_msg_routing_data_parents_no() {
        return (int)getUIntBEElement(offsetBits_data_msg_routing_data_parents_no(), 16);
    }

    /**
     * Set the value of the field 'data_msg.routing_data.parents_no'
     */
    public void set_data_msg_routing_data_parents_no(int value) {
        setUIntBEElement(offsetBits_data_msg_routing_data_parents_no(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'data_msg.routing_data.parents_no'
     */
    public static int size_data_msg_routing_data_parents_no() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'data_msg.routing_data.parents_no'
     */
    public static int sizeBits_data_msg_routing_data_parents_no() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data_msg.routing_data.parents.addr
    //   Field type: int[]
    //   Offset (bits): 0
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data_msg.routing_data.parents.addr' is signed (false).
     */
    public static boolean isSigned_data_msg_routing_data_parents_addr() {
        return false;
    }

    /**
     * Return whether the field 'data_msg.routing_data.parents.addr' is an array (true).
     */
    public static boolean isArray_data_msg_routing_data_parents_addr() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'data_msg.routing_data.parents.addr'
     */
    public static int offset_data_msg_routing_data_parents_addr(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 3) throw new ArrayIndexOutOfBoundsException();
        offset += 224 + index1 * 64;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data_msg.routing_data.parents.addr'
     */
    public static int offsetBits_data_msg_routing_data_parents_addr(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 3) throw new ArrayIndexOutOfBoundsException();
        offset += 224 + index1 * 64;
        return offset;
    }

    /**
     * Return the entire array 'data_msg.routing_data.parents.addr' as a int[]
     */
    public int[] get_data_msg_routing_data_parents_addr() {
        int[] tmp = new int[3];
        for (int index0 = 0; index0 < numElements_data_msg_routing_data_parents_addr(0); index0++) {
            tmp[index0] = getElement_data_msg_routing_data_parents_addr(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'data_msg.routing_data.parents.addr' from the given int[]
     */
    public void set_data_msg_routing_data_parents_addr(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_data_msg_routing_data_parents_addr(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'data_msg.routing_data.parents.addr'
     */
    public int getElement_data_msg_routing_data_parents_addr(int index1) {
        return (int)getUIntBEElement(offsetBits_data_msg_routing_data_parents_addr(index1), 16);
    }

    /**
     * Set an element of the array 'data_msg.routing_data.parents.addr'
     */
    public void setElement_data_msg_routing_data_parents_addr(int index1, int value) {
        setUIntBEElement(offsetBits_data_msg_routing_data_parents_addr(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'data_msg.routing_data.parents.addr'
     */
    public static int totalSize_data_msg_routing_data_parents_addr() {
        return (192 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'data_msg.routing_data.parents.addr'
     */
    public static int totalSizeBits_data_msg_routing_data_parents_addr() {
        return 192;
    }

    /**
     * Return the size, in bytes, of each element of the array 'data_msg.routing_data.parents.addr'
     */
    public static int elementSize_data_msg_routing_data_parents_addr() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'data_msg.routing_data.parents.addr'
     */
    public static int elementSizeBits_data_msg_routing_data_parents_addr() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'data_msg.routing_data.parents.addr'
     */
    public static int numDimensions_data_msg_routing_data_parents_addr() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'data_msg.routing_data.parents.addr'
     */
    public static int numElements_data_msg_routing_data_parents_addr() {
        return 3;
    }

    /**
     * Return the number of elements in the array 'data_msg.routing_data.parents.addr'
     * for the given dimension.
     */
    public static int numElements_data_msg_routing_data_parents_addr(int dimension) {
      int array_dims[] = { 3,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data_msg.routing_data.parents.etx
    //   Field type: int[]
    //   Offset (bits): 16
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data_msg.routing_data.parents.etx' is signed (false).
     */
    public static boolean isSigned_data_msg_routing_data_parents_etx() {
        return false;
    }

    /**
     * Return whether the field 'data_msg.routing_data.parents.etx' is an array (true).
     */
    public static boolean isArray_data_msg_routing_data_parents_etx() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'data_msg.routing_data.parents.etx'
     */
    public static int offset_data_msg_routing_data_parents_etx(int index1) {
        int offset = 16;
        if (index1 < 0 || index1 >= 3) throw new ArrayIndexOutOfBoundsException();
        offset += 224 + index1 * 64;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data_msg.routing_data.parents.etx'
     */
    public static int offsetBits_data_msg_routing_data_parents_etx(int index1) {
        int offset = 16;
        if (index1 < 0 || index1 >= 3) throw new ArrayIndexOutOfBoundsException();
        offset += 224 + index1 * 64;
        return offset;
    }

    /**
     * Return the entire array 'data_msg.routing_data.parents.etx' as a int[]
     */
    public int[] get_data_msg_routing_data_parents_etx() {
        int[] tmp = new int[3];
        for (int index0 = 0; index0 < numElements_data_msg_routing_data_parents_etx(0); index0++) {
            tmp[index0] = getElement_data_msg_routing_data_parents_etx(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'data_msg.routing_data.parents.etx' from the given int[]
     */
    public void set_data_msg_routing_data_parents_etx(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_data_msg_routing_data_parents_etx(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'data_msg.routing_data.parents.etx'
     */
    public int getElement_data_msg_routing_data_parents_etx(int index1) {
        return (int)getUIntBEElement(offsetBits_data_msg_routing_data_parents_etx(index1), 16);
    }

    /**
     * Set an element of the array 'data_msg.routing_data.parents.etx'
     */
    public void setElement_data_msg_routing_data_parents_etx(int index1, int value) {
        setUIntBEElement(offsetBits_data_msg_routing_data_parents_etx(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'data_msg.routing_data.parents.etx'
     */
    public static int totalSize_data_msg_routing_data_parents_etx() {
        return (192 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'data_msg.routing_data.parents.etx'
     */
    public static int totalSizeBits_data_msg_routing_data_parents_etx() {
        return 192;
    }

    /**
     * Return the size, in bytes, of each element of the array 'data_msg.routing_data.parents.etx'
     */
    public static int elementSize_data_msg_routing_data_parents_etx() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'data_msg.routing_data.parents.etx'
     */
    public static int elementSizeBits_data_msg_routing_data_parents_etx() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'data_msg.routing_data.parents.etx'
     */
    public static int numDimensions_data_msg_routing_data_parents_etx() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'data_msg.routing_data.parents.etx'
     */
    public static int numElements_data_msg_routing_data_parents_etx() {
        return 3;
    }

    /**
     * Return the number of elements in the array 'data_msg.routing_data.parents.etx'
     * for the given dimension.
     */
    public static int numElements_data_msg_routing_data_parents_etx(int dimension) {
      int array_dims[] = { 3,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data_msg.routing_data.parents.periods
    //   Field type: int[]
    //   Offset (bits): 32
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data_msg.routing_data.parents.periods' is signed (false).
     */
    public static boolean isSigned_data_msg_routing_data_parents_periods() {
        return false;
    }

    /**
     * Return whether the field 'data_msg.routing_data.parents.periods' is an array (true).
     */
    public static boolean isArray_data_msg_routing_data_parents_periods() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'data_msg.routing_data.parents.periods'
     */
    public static int offset_data_msg_routing_data_parents_periods(int index1) {
        int offset = 32;
        if (index1 < 0 || index1 >= 3) throw new ArrayIndexOutOfBoundsException();
        offset += 224 + index1 * 64;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data_msg.routing_data.parents.periods'
     */
    public static int offsetBits_data_msg_routing_data_parents_periods(int index1) {
        int offset = 32;
        if (index1 < 0 || index1 >= 3) throw new ArrayIndexOutOfBoundsException();
        offset += 224 + index1 * 64;
        return offset;
    }

    /**
     * Return the entire array 'data_msg.routing_data.parents.periods' as a int[]
     */
    public int[] get_data_msg_routing_data_parents_periods() {
        int[] tmp = new int[3];
        for (int index0 = 0; index0 < numElements_data_msg_routing_data_parents_periods(0); index0++) {
            tmp[index0] = getElement_data_msg_routing_data_parents_periods(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'data_msg.routing_data.parents.periods' from the given int[]
     */
    public void set_data_msg_routing_data_parents_periods(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_data_msg_routing_data_parents_periods(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'data_msg.routing_data.parents.periods'
     */
    public int getElement_data_msg_routing_data_parents_periods(int index1) {
        return (int)getUIntBEElement(offsetBits_data_msg_routing_data_parents_periods(index1), 16);
    }

    /**
     * Set an element of the array 'data_msg.routing_data.parents.periods'
     */
    public void setElement_data_msg_routing_data_parents_periods(int index1, int value) {
        setUIntBEElement(offsetBits_data_msg_routing_data_parents_periods(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'data_msg.routing_data.parents.periods'
     */
    public static int totalSize_data_msg_routing_data_parents_periods() {
        return (192 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'data_msg.routing_data.parents.periods'
     */
    public static int totalSizeBits_data_msg_routing_data_parents_periods() {
        return 192;
    }

    /**
     * Return the size, in bytes, of each element of the array 'data_msg.routing_data.parents.periods'
     */
    public static int elementSize_data_msg_routing_data_parents_periods() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'data_msg.routing_data.parents.periods'
     */
    public static int elementSizeBits_data_msg_routing_data_parents_periods() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'data_msg.routing_data.parents.periods'
     */
    public static int numDimensions_data_msg_routing_data_parents_periods() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'data_msg.routing_data.parents.periods'
     */
    public static int numElements_data_msg_routing_data_parents_periods() {
        return 3;
    }

    /**
     * Return the number of elements in the array 'data_msg.routing_data.parents.periods'
     * for the given dimension.
     */
    public static int numElements_data_msg_routing_data_parents_periods(int dimension) {
      int array_dims[] = { 3,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data_msg.routing_data.parents.subunits
    //   Field type: int[]
    //   Offset (bits): 48
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data_msg.routing_data.parents.subunits' is signed (false).
     */
    public static boolean isSigned_data_msg_routing_data_parents_subunits() {
        return false;
    }

    /**
     * Return whether the field 'data_msg.routing_data.parents.subunits' is an array (true).
     */
    public static boolean isArray_data_msg_routing_data_parents_subunits() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'data_msg.routing_data.parents.subunits'
     */
    public static int offset_data_msg_routing_data_parents_subunits(int index1) {
        int offset = 48;
        if (index1 < 0 || index1 >= 3) throw new ArrayIndexOutOfBoundsException();
        offset += 224 + index1 * 64;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data_msg.routing_data.parents.subunits'
     */
    public static int offsetBits_data_msg_routing_data_parents_subunits(int index1) {
        int offset = 48;
        if (index1 < 0 || index1 >= 3) throw new ArrayIndexOutOfBoundsException();
        offset += 224 + index1 * 64;
        return offset;
    }

    /**
     * Return the entire array 'data_msg.routing_data.parents.subunits' as a int[]
     */
    public int[] get_data_msg_routing_data_parents_subunits() {
        int[] tmp = new int[3];
        for (int index0 = 0; index0 < numElements_data_msg_routing_data_parents_subunits(0); index0++) {
            tmp[index0] = getElement_data_msg_routing_data_parents_subunits(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'data_msg.routing_data.parents.subunits' from the given int[]
     */
    public void set_data_msg_routing_data_parents_subunits(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_data_msg_routing_data_parents_subunits(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'data_msg.routing_data.parents.subunits'
     */
    public int getElement_data_msg_routing_data_parents_subunits(int index1) {
        return (int)getUIntBEElement(offsetBits_data_msg_routing_data_parents_subunits(index1), 16);
    }

    /**
     * Set an element of the array 'data_msg.routing_data.parents.subunits'
     */
    public void setElement_data_msg_routing_data_parents_subunits(int index1, int value) {
        setUIntBEElement(offsetBits_data_msg_routing_data_parents_subunits(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'data_msg.routing_data.parents.subunits'
     */
    public static int totalSize_data_msg_routing_data_parents_subunits() {
        return (192 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'data_msg.routing_data.parents.subunits'
     */
    public static int totalSizeBits_data_msg_routing_data_parents_subunits() {
        return 192;
    }

    /**
     * Return the size, in bytes, of each element of the array 'data_msg.routing_data.parents.subunits'
     */
    public static int elementSize_data_msg_routing_data_parents_subunits() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'data_msg.routing_data.parents.subunits'
     */
    public static int elementSizeBits_data_msg_routing_data_parents_subunits() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'data_msg.routing_data.parents.subunits'
     */
    public static int numDimensions_data_msg_routing_data_parents_subunits() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'data_msg.routing_data.parents.subunits'
     */
    public static int numElements_data_msg_routing_data_parents_subunits() {
        return 3;
    }

    /**
     * Return the number of elements in the array 'data_msg.routing_data.parents.subunits'
     * for the given dimension.
     */
    public static int numElements_data_msg_routing_data_parents_subunits(int dimension) {
      int array_dims[] = { 3,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

}
