#!/bin/sh
mv CollectionC.nc.patch ctp/
mv CtpForwardingEngineP.nc.patch ctp/
mv CtpP.nc.patch ctp/
mv CtpRoutingEngineP.nc.patch ctp/
mv CtpRadioSettingsP.nc ctp/
mv CtpClear.nc ctp/
mv CtpRadioSettings.nc ctp/
mv LinkEstimatorC.nc.patch le/
mv LinkEstimatorP.nc.patch le/
cd ctp/
patch -p0 < CollectionC.nc.patch
patch -p0 < CtpForwardingEngineP.nc.patch
patch -p0 < CtpP.nc.patch
patch -p0 < CtpRoutingEngineP.nc.patch
cd ../le/
patch -p0 < LinkEstimatorC.nc.patch
patch -p0 < LinkEstimatorP.nc.patch

