/**
 * This class is automatically generated by ncg. DO NOT EDIT THIS FILE.
 * This class includes values of some nesC constants from
 * ../nesc/PLR/PLR.h.
 */

package netTest;

public class Constants  {
    public static final byte MIN_SEND_PACKET_TIME = 10;
    public static final byte MAX_STATS_RETX = 2;
    public static final byte RX_SIZE = 16;
    public static final byte LPL_PLR = 2;
    public static final byte MAC_PLR = 1;
    public static final char REPORT_RETRY_INTERVAL = 60000;
    public static final byte PURE_PLR = 0;
    public static final byte NR_NODES = 5;
    public static final byte PAYLOAD_LENGTH = 94;
}
